services:
  nestjs-puppeteer-app:
    platform: linux/amd64
    image: nestjs-puppeteer:develop
    container_name: nestjs-puppeteer-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    restart: always
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./screenshot:/app/scheenshot
    ports:
      - 3100:3100
