services:
  nestjs-puppeteer-app:
    platform: linux/amd64
    image: 982860581031.dkr.ecr.ap-southeast-1.amazonaws.com/auto-checkin:1.0
    container_name: autocheckin-1.0
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    restart: always
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./screenshot:/app/scheenshot
      - ./downloads:/app/downloads
    ports:
      - 3100:3100
