services:
  nestjs-puppeteer-app:
    platform: linux/amd64
    image: marutora7876/nestjs-puppeteer:prototype
    container_name: nestjs-puppeteer-app
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
