apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example4
  name: example4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example4
  template:
    metadata:
      labels:
        app: example4
    spec:
      containers:
        - image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          name: nestjs-puppetter-example-4
          ports:
            - containerPort: 3002
          env:
            # Example of None Secret ENV
            - name: NODE_ENV
              value: production
            - name: APP_NAME
              value: example4
            - name: APP_PORT
              value: 3004
            - name: APP_DEEP_SECRET_ONE
              valueFrom:
                secretKeyRef:
                  name: example4
                  key: dank4
            - name: APP_DEEP_SECRET_TWO
              valueFrom:
                secretKeyRef:
                  name: example4
                  key: dank4
