apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example4
  name: example4
  namespace: example4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example4
  template:
    metadata:
      labels:
        app: example4
    spec:
      containers:
        - image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          name: nestjs-puppetter-example-4
          ports:
            - containerPort: 3002
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: example4
                  key: NODE_ENV

            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: example4
                  key: APP_NAME

            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: example4
                  key: APP_PORT

            - name: APP_WEB_URL
              valueFrom:
                configMapKeyRef:
                  name: example4
                  key: APP_WEB_URL
