apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example3
  name: example3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example3
  template:
    metadata:
      labels:
        app: example3
    spec:
      containers:
        - image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          name: nestjs-puppetter-example-3
          ports:
            - containerPort: 3002
          env:
            # Example of None Secret ENV
            - name: NODE_ENV
              value: production
            - name: APP_NAME
              value: example3
            - name: APP_PORT
              value: 3003
            - name: APP_DEEP_SECRET_ONE
              valueFrom:
                secretKeyRef:
                  name: example3
                  key: dank3
            - name: APP_DEEP_SECRET_TWO
              valueFrom:
                secretKeyRef:
                  name: example3
                  key: dank3
