apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example6
  name: example6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example6
  template:
    metadata:
      labels:
        app: example6
    spec:
      containers:
        - image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          name: nestjs-puppetter-example-6
          ports:
            - containerPort: 3002
          env:
            # Example of None Secret ENV
            - name: NODE_ENV
              value: production
            - name: APP_NAME
              value: example6
            - name: APP_PORT
              value: 3006
            - name: APP_DEEP_SECRET_ONE
              valueFrom:
                secretKeyRef:
                  name: example6
                  key: dank6
            - name: APP_DEEP_SECRET_TWO
              valueFrom:
                secretKeyRef:
                  name: example6
                  key: dank6
