apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example9
  name: example9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example9
  template:
    metadata:
      labels:
        app: example9
    spec:
      containers:
        - image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          name: nestjs-puppetter-example-9
          ports:
            - containerPort: 3009
          env:
            # Example of None Secret ENV
            - name: NODE_ENV
              value: production
            - name: APP_NAME
              value: example9
            - name: APP_PORT
              value: 3009
            - name: APP_DEEP_SECRET_ONE
              valueFrom:
                secretKeyRef:
                  name: example9
                  key: dank9
            - name: APP_DEEP_SECRET_TWO
              valueFrom:
                secretKeyRef:
                  name: example9
                  key: dank9
