apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example7
  name: example7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example7
  template:
    metadata:
      labels:
        app: example7
    spec:
      containers:
        - image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          name: nestjs-puppetter-example-7
          ports:
            - containerPort: 3007
          env:
            # Example of None Secret ENV
            - name: NODE_ENV
              value: production
            - name: APP_NAME
              value: example7
            - name: APP_PORT
              value: 3007
            - name: APP_DEEP_SECRET_ONE
              valueFrom:
                secretKeyRef:
                  name: example7
                  key: dank7
            - name: APP_DEEP_SECRET_TWO
              valueFrom:
                secretKeyRef:
                  name: example7
                  key: dank7
