# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: example2
#   name: example2
# spec:
#   ports:
#     - name: 'http'
#       port: 3002
#       protocol: TCP
#       targetPort: 3002
#   selector:
#     app: example2
#   type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: example7
  namespace: example7
spec:
  selector:
    app: example7
  ports:
    - protocol: TCP
      port: 3007
  type: LoadBalancer
