apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example10
  name: example10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example10
  template:
    metadata:
      labels:
        app: example10
    spec:
      containers:
        - image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          name: nestjs-puppetter-example-10
          ports:
            - containerPort: 3010
          env:
            # Example of None Secret ENV
            - name: NODE_ENV
              value: production
            - name: APP_NAME
              value: example10
            - name: APP_PORT
              value: 3010
            - name: APP_DEEP_SECRET_ONE
              valueFrom:
                secretKeyRef:
                  name: example10
                  key: dank10
            - name: APP_DEEP_SECRET_TWO
              valueFrom:
                secretKeyRef:
                  name: example10
                  key: dank10
