apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example5
  name: example5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example5
  template:
    metadata:
      labels:
        app: example5
    spec:
      containers:
        - image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          name: nestjs-puppetter-example-5
          ports:
            - containerPort: 3002
          env:
            # Example of None Secret ENV
            - name: NODE_ENV
              value: production
            - name: APP_NAME
              value: example5
            - name: APP_PORT
              value: 3005
            - name: APP_DEEP_SECRET_ONE
              valueFrom:
                secretKeyRef:
                  name: example5
                  key: dank5
            - name: APP_DEEP_SECRET_TWO
              valueFrom:
                secretKeyRef:
                  name: example5
                  key: dank5
