apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example1
  name: example1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example1
  template:
    metadata:
      labels:
        app: example1
    spec:
      containers:
        - image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
          name: nestjs-puppetter-example-1
          ports:
            - containerPort: 3001
          env:
            # Example of None Secret ENV
            - name: NODE_ENV
              value: production
            - name: APP_NAME
              value: example-1
            - name: APP_PORT
              value: '3001'
            - name: APP_DEEP_SECRET_ONE
              valueFrom:
                secretKeyRef:
                  name: example1
                  key: dank1
            - name: APP_DEEP_SECRET_TWO
              valueFrom:
                secretKeyRef:
                  name: example2
                  key: dank2
