# NodePort type

# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: example1
#   name: example1
# spec:
#   ports:
#     - name: 'http'
#       port: 3001
#       protocol: TCP
#       targetPort: 3001
#   selector:
#     app: example1
#   type: NodePort
# Load Balancer Type

apiVersion: v1
kind: Service
metadata:
  name: example1
  namespace: example1
spec:
  selector:
    app: example1
  ports:
    - protocol: TCP
      port: 3001
  type: LoadBalancer
